# These are supported funding model platforms

github: [aduskin]
patreon: aduskin
open_collective: AduSkin
ko_fi: aduskin
tidelift: npm/cdn
issuehunt: aduskin
custom: custom: ["https://paypal.me/aduskin3821", 杜召]
